language: php

php:
  - 7.4
  - 8.1

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - echo 'xdebug.mode = coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --no-interaction

script: bin/kahlan --coverage=3 --clover=clover.xml --reporter=verbose

after_success:
  - "if [ $(phpenv version-name) = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.4' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    - secure: mSQyMz28KSMgztAa85fHEck9D+2mMgWCktLKjSCv7AciSlLfdEWhgJudwznrSR8pK4tCigh+4XcbH4RvttYkGB5CXd4J0rtZk0r6K/WRs2L3lCr4JihvYbrymp3F8A4yERKqKd6fbIhrk+Nfnl+F7ixh6ZWi9bxs7Rsfsb8B8UBVYNHlTKmj8AfpRnQCnyXYhQzTCAnzha+aQsLmqOrmWs+8vseSeOSaW0NZ/mE6TtlZOpjX8xMhxZzuTEwQisCVsLe0pGHIJE9I7pPTt+7mpNba2HCAFLEL0tZR/5PBJ6rkCS3BuyCNPYGnMFC5HoM8pKckNAgqzk56Bq3iUMS0ahB7gnw3/jHsXh+y9sP1ejMLmruDgn11+RxPg/M6pdyrVteKH5vJOl6KqO4doWOKyHnV4ceAYgZQg+ej3xC6WhxYIlFZ/RkocYxCHt1b8PZy0oF2YxwSKfY4/EkRJi6KZKSbhwgQw+eJM2/u4Gp+186EU0TYCeL1872FEAg3RN/urzjilQFfK8PvzRvFbTqR/fqj5mf1bl8uYyNC6hwZjOyYO5JtwjLGYVlpomDMiLWmzvgrgdUputvZiULHgidg82vcg1sh0dlslrKZsawHCdrpjYNUFqffN1jU6rm7c2cQ+HO3phrzU3yFfJ3vWHJeiUXIFa7xl+aT/vJkvaRU6mQ=
